permalink: /:title
title: list.her.sh
url: https://list.her.sh
highlighter: pygments

exclude: [Gemfile, Gemfile.lock, readme.md, Rakefile, vendor, circle.yml]

parent:
  name: her.sh
  url: https://her.sh

feedurl: https://list.her.sh/atom.xml
sourceurl: https://github.com/jhersh/list.her.sh

author:
  name: Jonathan Hersh
  email: jon@her.sh

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
