version: '2.1'

jobs:
  build:
    docker:
        - image: cimg/ruby:3.1.2
    working_directory: ~/list.her.sh
    environment:
      - JEKYLL_ENV: "production"
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: |
          sudo apt-get install curl python-software-properties
          curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
          sudo apt-get install nodejs
          node -v
          sudo npm install -g write-good
      - run: rake setup
      - run: rake build
      - run: rake lint
      - persist_to_workspace:
          root: ~/list.her.sh
          paths: _site
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  deploy:
    docker:
        - image: cimg/python:3.11.0
    working_directory: ~/list.her.sh
    steps:
      - checkout
      - run: |
          pip install s3cmd
          s3cmd --version
      - attach_workspace:
          at: ~/list.her.sh
      - run: .circleci/publish.sh
      
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          context: Pushover
          requires: 
            - build
          filters:
            branches:
              only: master
